### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by kerigen** [MattePalte/Verbify-TTS#17]
when I run the command_read.py in terminal I get this error message:
**File "/home/xxx/xxx/Verbify-TTS/command_read.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'**

I checked to see if REQUESTS is installed with command "pip show requests " and this is what I got:

**Name: requests
Version: 2.28.1
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/lib/python3/dist-packages**

**Comment by JeremyBickel** [comment]
Did you run server.py? If not, run it and switch to a new shell, then try the read command.

**Comment by dan-frohlich** [comment]
same error.
Also when I run `server.py`...

```
Verbify-TTS$ ./env/bin/python ./server.py 
Traceback (most recent call last):
  File "/media/dan/big_country/code/Verbify-TTS/./server.py", line 15, in <module>
    from flask import Flask, request, jsonify
ModuleNotFoundError: No module named 'flask'
```
