### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by mpeschulz** [MattePalte/Verbify-TTS#7]
I get the following error message. Do you have any suggestion?
I am using ubuntu  22.04.2 LTS
Thank you!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mschulz/Verbify-TTS/command_read.py", line 43, in <module>
    r = requests.post(f'http://0.0.0.0:{config["server_port"]}/api', json=payload)
  File "/home/mschulz/.local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/mschulz/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mschulz/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mschulz/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mschulz/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=5069): Max retries exceeded with url: /api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddf4c3b2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by kisdia** [comment]
Same issue.
